"""Stage tests — stub the LLM, verify each stage produces the right file + state transition.

Runs entirely offline. No API keys required.
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from state import new_state, save_state, load_state  # noqa: E402
from llm import LLMResult  # noqa: E402


def fake_llm_result(text: str = "# Fake dossier\n\nGenerated by test.", model: str = "gemini-2.0-pro-exp") -> LLMResult:
    return LLMResult(text=text, tokens_in=100, tokens_out=200, model=model)


def make_book(tmp_path: Path, book_id: str = "test-book", status: str = "Brief received") -> Path:
    """Create a book folder + state.json in a temp books root."""
    s = new_state(
        book_id=book_id,
        working_title="Test Book",
        subtitle="A Test Subtitle",
        prompt_template="vocabulary-reference-v1",
        one_line_brief="A test book brief.",
        entry_count_target=10,  # small for tests
    )
    s["status"] = status
    save_state(tmp_path, book_id, s)
    return tmp_path


@patch("llm.call_llm")
def test_stage_01_dossier(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# Test dossier\n\nContent here.")
    make_book(tmp_path)

    from stage_01_dossier import run
    run(tmp_path, "test-book")

    dossier = tmp_path / "books" / "test-book" / "01-dossier.md"
    assert dossier.exists()
    assert "Test dossier" in dossier.read_text()

    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Dossier ready — awaiting review"
    assert "dossier" in s["stages_completed"]
    assert s["assets_generated"]["dossier"] is not None


@patch("llm.call_llm")
def test_stage_02_structure(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# Structure\n\n## De Watuh — target: 4")
    make_book(tmp_path, status="Dossier ready — awaiting review")

    from stage_02_structure import run
    run(tmp_path, "test-book")

    assert (tmp_path / "books" / "test-book" / "02-structure.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Structure ready — awaiting review"


@patch("llm.call_llm")
def test_stage_03_entries_batches_and_resumes(mock_llm, tmp_path):
    # Each call returns 2 entries; target 4 across 1 section
    fake_entries = [
        [{"headword": "a", "pronunciation": "ay", "english_definition": "the letter a"},
         {"headword": "b", "pronunciation": "bee", "english_definition": "the letter b"}],
        [{"headword": "c", "pronunciation": "see", "english_definition": "the letter c"},
         {"headword": "d", "pronunciation": "dee", "english_definition": "the letter d"}],
    ]
    call_count = {"n": 0}

    def side_effect(*args, **kwargs):
        batch = fake_entries[call_count["n"] % len(fake_entries)]
        call_count["n"] += 1
        return fake_llm_result(text=json.dumps(batch))

    mock_llm.side_effect = side_effect

    make_book(tmp_path, status="Structure ready — awaiting review")
    book_dir = tmp_path / "books" / "test-book"
    # Provide a structure doc so parse_sections_from_structure has something
    (book_dir / "02-structure.md").write_text(
        "# Structure\n\n## De Watuh — target: 4\n"
    )

    # Force entry_count_target to 4 so this test finishes quickly
    s = load_state(tmp_path, "test-book")
    s["entry_count_target"] = 4
    save_state(tmp_path, "test-book", s)

    from stage_03_entries import run
    run(tmp_path, "test-book")

    s = load_state(tmp_path, "test-book")
    # After 4 entries collected, status should flip
    assert s["assets_generated"]["entries_count"] >= 4
    assert s["status"] in {"Entries ready — awaiting review", "Entries generating"}


@patch("llm.call_llm")
def test_stage_04_sample_chapter(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# De Watuh\n\nSample chapter content.")
    make_book(tmp_path, status="Entries ready — awaiting review")
    book_dir = tmp_path / "books" / "test-book"
    (book_dir / "03-entries").mkdir(exist_ok=True)
    (book_dir / "03-entries" / "de-watuh.json").write_text(json.dumps([
        {"headword": "watuh", "pronunciation": "WAH-tuh", "english_definition": "water"}
    ]))

    from stage_04_sample_chapter import run
    run(tmp_path, "test-book")

    assert (book_dir / "04-sample-chapter.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Sample chapter ready — awaiting review"


@patch("llm.call_llm")
def test_stage_05_kdp_metadata(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# KDP Metadata\n\n...")
    make_book(tmp_path, status="Sample chapter ready — awaiting review")

    from stage_05_kdp_metadata import run
    run(tmp_path, "test-book")

    assert (tmp_path / "books" / "test-book" / "05-kdp-metadata.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Social assets drafting"


@patch("llm.call_llm")
def test_stage_06_social_all_substages(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("Social content")
    make_book(tmp_path, status="Social assets drafting")

    from stage_06_social import run
    run(tmp_path, "test-book")

    book_dir = tmp_path / "books" / "test-book"
    assert (book_dir / "06-pins.md").exists()
    assert (book_dir / "07-tiktok-script.md").exists()
    assert (book_dir / "08-shorts-script.md").exists()
    assert (book_dir / "09-substack-teaser.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "ACX brief drafting"


@patch("llm.call_llm")
def test_stage_10_acx(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# ACX Brief")
    make_book(tmp_path, status="ACX brief drafting")

    from stage_10_acx import run
    run(tmp_path, "test-book")

    assert (tmp_path / "books" / "test-book" / "10-acx-brief.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Rights & IP drafting"


@patch("llm.call_llm")
def test_stage_11_rights(mock_llm, tmp_path):
    mock_llm.return_value = fake_llm_result("# Rights & IP")
    make_book(tmp_path, status="Rights & IP drafting")

    from stage_11_rights import run
    run(tmp_path, "test-book")

    assert (tmp_path / "books" / "test-book" / "11-rights-ip.md").exists()
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Package assembly"


def test_stage_12_assemble_produces_zip(tmp_path):
    # No LLM call for this stage
    make_book(tmp_path, status="Package assembly")
    book_dir = tmp_path / "books" / "test-book"
    # Seed some files
    (book_dir / "01-dossier.md").write_text("# Dossier")
    (book_dir / "02-structure.md").write_text("# Structure")
    (book_dir / "03-entries").mkdir(exist_ok=True)
    (book_dir / "03-entries" / "de-watuh.json").write_text("[]")
    (book_dir / "11-rights-ip.md").write_text("# Rights")

    from stage_12_assemble import run
    run(tmp_path, "test-book")

    kit = book_dir / "final-kit.zip"
    assert kit.exists()
    assert kit.stat().st_size > 0
    s = load_state(tmp_path, "test-book")
    assert s["status"] == "Ready for KDP handoff"
    assert s["assets_generated"]["final_kit"] is not None


def test_new_book_script_intake(tmp_path):
    """new_book.py creates folder + state.json + brief.md with correct defaults."""
    import subprocess
    result = subprocess.run([
        sys.executable, str(REPO_ROOT / "scripts" / "new_book.py"),
        "--books-root", str(tmp_path),
        "--book-id", "smoke-test",
        "--title", "Smoke Test",
        "--subtitle", "Smoke Subtitle",
        "--template", "vocabulary-reference-v1",
        "--brief", "Smoke test brief.",
        "--entry-count-target", "50",
    ], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr

    book_dir = tmp_path / "books" / "smoke-test"
    assert (book_dir / "state.json").exists()
    assert (book_dir / "brief.md").exists()
    s = load_state(tmp_path, "smoke-test")
    assert s["status"] == "Brief received"
    assert s["entry_count_target"] == 50
    assert s["author"] == "Darryl Elliott Brown"
    assert s["publisher"] == "Gullah Geechee Biz"
