"""Stage 12 — Assemble the final book kit ZIP.

Reads every generated file, builds a README, zips the book folder into
`final-kit.zip`, updates state to `Ready for KDP handoff`.

No LLM calls — pure file assembly. Uses zero API quota.
"""
from __future__ import annotations

import argparse
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from state import load_state, save_state, mark_error  # noqa: E402


KIT_FILES_ORDER = [
    ("00-README.md", None),
    ("brief.md", None),
    ("01-dossier.md", "dossier"),
    ("02-structure.md", "structure"),
    ("03-entries/", "entries_count"),
    ("04-sample-chapter.md", "sample_chapter"),
    ("05-kdp-metadata.md", "kdp_metadata"),
    ("06-pins.md", "pins_doc"),
    ("07-tiktok-script.md", "tiktok"),
    ("08-shorts-script.md", "shorts"),
    ("09-substack-teaser.md", "substack"),
    ("10-acx-brief.md", "acx_brief"),
    ("11-rights-ip.md", "rights_ip"),
]


def build_readme(state: dict) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    author = state.get("author", "Darryl Elliott Brown")
    publisher = state.get("publisher", "Gullah Geechee Biz")
    entries_count = state.get("assets_generated", {}).get("entries_count", 0)
    return f"""# {state.get('working_title', 'Untitled')}
## {state.get('subtitle', '')}

**Author:** {author}
**Publisher:** {publisher}
**Series:** {state.get('series', '')}
**Edition:** {state.get('edition', '')}
**Formats:** {', '.join(state.get('formats', []))}
**Corridor scope:** {', '.join(state.get('corridor_scope', []))}
**Assembled:** {now}

---

## What's in this kit

Generated by the GGB Book Pipeline v3.0 (zero-cost, GitHub-Actions-native, Gemini-powered).

| # | File | Purpose |
|---|---|---|
| 01 | `01-dossier.md` | Research dossier with sources, scholarly framing, cultural ethics |
| 02 | `02-structure.md` | 10-section architecture, front + back matter, headword counts |
| 03 | `03-entries/` | {entries_count} vocabulary entries across sections (JSON) |
| 04 | `04-sample-chapter.md` | Complete sample chapter |
| 05 | `05-kdp-metadata.md` | KDP + D2D listing pack, ISBN plan, categories, keywords |
| 06 | `06-pins.md` | 5 Pinterest pin briefs |
| 07 | `07-tiktok-script.md` | 75-second TikTok script |
| 08 | `08-shorts-script.md` | 55-second YouTube Shorts script |
| 09 | `09-substack-teaser.md` | Launch announcement post + subject lines |
| 10 | `10-acx-brief.md` | Audiobook narrator direction sheet |
| 11 | `11-rights-ip.md` | Rights, copyright, trademark, AI disclosure, DMCA |

---

## Pipeline metadata

- **Stages completed:** {', '.join(state.get('stages_completed', []))}
- **Cultural sensitivity level:** {state.get('cultural_sensitivity_level', 'Standard')}
- **Cash cost of production:** $0

---

*Mus tek cyear a de root, fa heal de tree.*
"""


def run(books_root: Path, book_id: str) -> None:
    state = load_state(books_root, book_id)
    book_dir = books_root / "books" / book_id

    # Update status
    state["status"] = "Package assembly"
    state["current_stage"] = "assemble"
    save_state(books_root, book_id, state)

    # Write README
    readme_path = book_dir / "00-README.md"
    readme_path.write_text(build_readme(state))

    # Build ZIP
    kit_path = book_dir / "final-kit.zip"
    if kit_path.exists():
        kit_path.unlink()

    added = 0
    with zipfile.ZipFile(kit_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for relpath, _ in KIT_FILES_ORDER:
            src = book_dir / relpath
            if relpath.endswith("/"):
                # Directory — walk it
                if src.exists() and src.is_dir():
                    for f in sorted(src.rglob("*")):
                        if f.is_file():
                            zf.write(f, arcname=f.relative_to(book_dir))
                            added += 1
            else:
                if src.exists() and src.is_file():
                    zf.write(src, arcname=relpath)
                    added += 1

    if added == 0:
        mark_error(books_root, book_id, "No files to assemble — kit would be empty.")
        raise RuntimeError("Empty kit")

    # Update state
    state = load_state(books_root, book_id)
    state["assets_generated"]["final_kit"] = str(kit_path.relative_to(books_root))
    if "assemble" not in state["stages_completed"]:
        state["stages_completed"].append("assemble")
    state["status"] = "Ready for KDP handoff"
    save_state(books_root, book_id, state)
    print(f"[assemble] Wrote {kit_path} with {added} files → status=Ready for KDP handoff")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--books-root", required=True)
    parser.add_argument("--book-id", required=True)
    args = parser.parse_args()
    run(Path(args.books_root), args.book_id)


if __name__ == "__main__":
    main()
